-- Arquivo: supabase_products.sql
-- Use no Dashboard do Supabase → SQL Editor → cole e execute.
-- Observação: para operações de escrita no painel você pode precisar da service_role key.

-- 1) Criar tabela products
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  brand text,
  category text,
  price numeric(10,2),
  status text,
  tag text,
  image text,
  stock text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2) Habilitar Row Level Security (recomendado no Supabase)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3) Política para permitir SELECT público via anon key
CREATE POLICY public_select ON public.products
  FOR SELECT
  USING (true);

-- 4) Política opcional: permitir INSERT apenas para usuários autenticados
CREATE POLICY auth_insert ON public.products
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.role() = 'authenticated');

-- 5) INSERTs de exemplo (seed)
INSERT INTO public.products (name, brand, category, price, status, tag, image, stock) VALUES
('Camiseta Oversized Respeito', 'nexus', 'camiseta', 119.90, 'available', 'Mais Vendido', 'oversized_respeito.jpg', 'Disponível agora'),
('Calça Cargo Utilitária ZL', 'nexus', 'calça', 229.90, 'available', 'Novo', 'cargo_heavy.jpg', 'Disponível agora'),
('Moletom Canguru nexus Syndicate', 'nexus', 'moletom', 249.90, 'upcoming', 'Em Breve', 'moletom_syndicate.jpg', 'Entrando em estoque em breve'),
('Tênis All Star', 'nike', 'tênis', 199.90, 'available', 'Clássico', 'nike_all_star.jpg', 'Disponível agora'),
('Camisa Nike', 'nike', 'camisa', 129.90, 'available', 'Essencial', 'nike_shirt.jpg', 'Disponível agora')
ON CONFLICT DO NOTHING;

-- 6) Exemplo de requisição GET via REST (use a anon key)
-- curl -H "apikey: <YOUR_ANON_KEY>" -H "Authorization: Bearer <YOUR_ANON_KEY>" "https://<your-project>.supabase.co/rest/v1/products?select=*"

-- 7) Observações de segurança
-- - A anon key lida com leitura; para criar/alterar tabelas use a service_role key.
-- - A service_role ignora RLS; mantenha-a segura e não a exponha no front-end.
